routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Painel\CandidatosControler;
use App\Http\Controllers\Painel\VagasControler;
use App\Http\Controllers\Painel\PainelControler;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('painel')->middleware(['auth'])->name('painel.')->group(function () {
    Route::get('/', [PainelControler::class, 'index'])->name('home');
    Route::get('/vagas/update-status/{vaga}', [VagasControler::class, 'updateStatus'])->name('vagas.update-status');
    Route::delete('/vagas', [VagasControler::class, 'destroyMass'])->name('vagas.destroy-mass');
    Route::resource('vagas', VagasControler::class, ['names'=>'vagas']);

    Route::delete('/candidatos', [CandidatosControler::class, 'destroyMass'])->name('candidatos.destroy-mass');
    Route::resource('candidatos', CandidatosControler::class, ['names'=>'candidatos']);
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Candidato.php
<?php

namespace App\Models;

use App\Traits\PublicId;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Candidato extends Authenticatable
{
    use HasFactory, PublicId, Notifiable;

    protected $table = 'candidatos';
    protected $fillable = [
        'public_id', 'nome', 'telefone', 'email', 'email_verified_at',
        'password', 'contratacao', 'status',
    ];

    public function candidaturas()
    {
        return $this->belongsToMany(Vaga::class, 'candidatos_rel_vagas', 'candidato_id', 'vaga_id')->withTimestamps();
    }
}

app/Http/Controllers/CandidatoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vaga;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CandidatoController extends Controller
{
    public function candidaturas()
    {
        $candidaturas = auth()->guard('candidato')->user()->candidaturas;
        return view('candidato.candidaturas', compact('candidaturas'));
    }

    public function candidatar(Request $request, $public_id)
    {
        $candidato = auth()->guard('candidato')->user()->id;

        $vaga = Vaga::where('status', 1)->where('public_id', $public_id)->firstOrFail();
        if(!$vaga->candidatos->contains( $candidato )) {
            $vaga->candidatos()->attach($candidato);
        }
        
        Session::flash('flash_message', 'Sua candidatura foi enviada com sucesso!');

        return redirect()->route('home');
    }
}

resources/views/candidatos/form.blade.php
@extends('layouts.template')

@section('maincontent')
<h2 class="">Gerenciamento de Candidatos</h2>

@if(Session::has('flash_message'))
    <div class="alert alert-success mb-5" role="alert">
        {{ Session::get('flash_message') }}
    </div>
@endif

<div class="container">
    <div class="row mb-5">
        <div class="col">
            <a href="{{ route('painel.candidatos.index') }}" class="btn btn-secondary btn-small float-end"><i class="bi bi-arrow-left-short"></i> Voltar</a>
        </div>
    </div>
    
    <form action="{{ isset($candidato) ? route('painel.candidatos.update', $candidato->public_id) : route('painel.candidatos.store') }}" class="row justify-content-md-center needs-validation" method="post">
        {{ isset($candidato) ? method_field('PUT') : '' }}
        @csrf

        <div class="col-6">
            @if ($errors->any())
                <ul class="row mb-4 list-group">
                    @foreach($errors->all() as $error)
                        <li class="list-group-item list-group-item-danger">{{$error}}</li>
                    @endforeach
                </ul>
            @endif
            
            <div class="mb-3 row">
                <label for="nome" class="col-sm-2 col-form-label">Nome</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="nome" value="{{ isset($candidato) ? $candidato->nome : old('nome') }}" required>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="email" class="col-sm-2 col-form-label">E-mail</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="email" value="{{ isset($candidato) ? $candidato->email : old('email') }}" required>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="telefone" class="col-sm-2 col-form-label">Telefone</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="telefone" value="{{ isset($candidato) ? $candidato->telefone : old('telefone') }}" required>
                </div>
            </div>

            <div class="mt-5 mb-3 row">
                <div class="col">
                    <h4>Candidaturas em andamento:</h4>
                    <ul>
                        @forelse ($candidato->candidaturas as $candidatura)
                            <li>&raquo; <a href="{{ route('painel.vagas.edit', $candidatura->public_id) }}" target="_blank">{{ $candidatura->cargo }}</a></li>
                        @empty
                            <li>
                                <small>Nenhuma candidatura até o momento!</small>
                            </li>
                        @endforelse
                    </ul>
                </div>
            </div>

            <div class="row">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/candidatos/index.blade.php
@extends('layouts.template')

@section('maincontent')
<h2 class="">Gerenciamento de Candidatos</h2>

@if(Session::has('flash_message'))
    <div class="alert alert-success mb-5" role="alert">
        {{ Session::get('flash_message') }}
    </div>
@endif

<div class="container">
    <div class="row mb-5 mt-4">
        <div class="col">
            <form action="{{ route('painel.candidatos.index') }}" method="get" class="row g-3 float-start">
                <div class="col-auto">
                  <label for="pesquisar" class="visually-hidden">Pesquisar...</label>
                  <input type="text" class="form-control" name="pesquisar" value="{{ request('pesquisar') }}" placeholder="Pesquisar por nome...">
                </div>
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary mb-3">Pesquisar</button>
                </div>
            </form>
        </div>
    </div>


    <a href="#" class="btn btn-outline-danger __action_remover"><i class="bi bi-trash"></i> Remover Selecionados</a>
    <form method="post" class="__form_remover" action="{{ route('painel.candidatos.destroy-mass') }}">
        @csrf
        @method('DELETE')
        <input type="hidden" name="checados" class="checados" value="">
    </form>


    <table class="table table-hover">
        <thead>
            <tr>
                <td scope="col">&nbsp;</td>
                <td scope="col"><a href="{{ route('painel.candidatos.index', ['pesquisar'=>request('pesquisar'), 'order' => 'public_id', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">ID</a></td>
                <td scope="col"><a href="{{ route('painel.candidatos.index', ['pesquisar'=>request('pesquisar'), 'order' => 'nome', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">Nome</a></td>
                <td scope="col"><a href="{{ route('painel.candidatos.index', ['pesquisar'=>request('pesquisar'), 'order' => 'email', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">E-mail</a></td>
                <td scope="col"><a href="{{ route('painel.candidatos.index', ['pesquisar'=>request('pesquisar'), 'order' => 'telefone', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">Telefone</a></td>
                <td scope="col">N. Candidaturas</td>
                <td scope="col">&nbsp;</td>
                <td scope="col">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
        @forelse ($candidatos as $candidato)
            <tr>
                <td scope="row">
                    <input type="checkbox" name="candidatos[]" value="{{ $candidato->public_id }}" class="__checks">
                </td>
                <td>{{ $candidato->public_id }}</td>
                <td>{{ $candidato->nome }}</td>
                <td>{{ $candidato->email }}</td>
                <td>{{ $candidato->telefone }}</td>
                <td>{{ $candidato->candidaturas->count() }} Candidatura{{ $candidato->candidaturas->count() != 1 ? 's' : '' }}</td>
                <td>
                    <a href="{{ route('painel.candidatos.edit', $candidato->public_id) }}" class="btn btn-light btn-small">Editar</a>
                </td>
                <td>
                    <form action="{{ route('painel.candidatos.destroy', $candidato->public_id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-small">Excluir</button>
                    </form>
                </td>
            </tr>
        @empty
        <tr>
            <td colspan="8">
                Nenhuma candidato cadastrado até o momento!
            </td>
        </tr>
        @endforelse
        </tbody>
    </table>

    <div class="row justify-content-center">
        <div class="col">
            {{ $candidatos->appends(['pesquisar'=>request('pesquisar'), 'order'=>request('order'), 'orderby'=>request('orderby')])->links() }}
        </div>
    </div>
</div>
@endsection