routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Painel\CandidatosControler;
use App\Http\Controllers\Painel\VagasControler;
use App\Http\Controllers\Painel\PainelControler;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('painel')->middleware(['auth'])->name('painel.')->group(function () {
    Route::get('/', [PainelControler::class, 'index'])->name('home');
    Route::get('/vagas/update-status/{vaga}', [VagasControler::class, 'updateStatus'])->name('vagas.update-status');
    Route::delete('/vagas', [VagasControler::class, 'destroyMass'])->name('vagas.destroy-mass');
    Route::resource('vagas', VagasControler::class, ['names'=>'vagas']);

    Route::delete('/candidatos', [CandidatosControler::class, 'destroyMass'])->name('candidatos.destroy-mass');
    Route::resource('candidatos', CandidatosControler::class, ['names'=>'candidatos']);
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Vaga.php
<?php

namespace App\Models;

use App\Traits\PublicId;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vaga extends Model
{
    use HasFactory, PublicId;

    protected $table = 'vagas';
    protected $fillable = [
        'public_id', 'cargo', 'descricao', 'contratacao', 'status',
    ];

    public function candidatos()
    {
        return $this->belongsToMany(Candidato::class, 'candidatos_rel_vagas', 'vaga_id', 'candidato_id')->withTimestamps();
    }
}

resources/views/vagas/form.blade.php
@extends('layouts.template')

@section('maincontent')
<h2 class="">Gerenciamento de Vagas</h2>

@if(Session::has('flash_message'))
    <div class="alert alert-success mb-5" role="alert">
        {{ Session::get('flash_message') }}
    </div>
@endif

<div class="container">
    <div class="row mb-5">
        <div class="col">
            <a href="{{ route('painel.vagas.index') }}" class="btn btn-secondary btn-small float-end"><i class="bi bi-arrow-left-short"></i> Voltar</a>
        </div>
    </div>
    
    <form action="{{ isset($vaga) ? route('painel.vagas.update', $vaga->public_id) : route('painel.vagas.store') }}" class="row justify-content-md-center needs-validation" method="post">
        {{ isset($vaga) ? method_field('PUT') : '' }}
        @csrf

        <div class="col-6">
            @if ($errors->any())
                <ul class="row mb-4 list-group">
                    @foreach($errors->all() as $error)
                        <li class="list-group-item list-group-item-danger">{{$error}}</li>
                    @endforeach
                </ul>
            @endif
            
            <div class="mb-3 row">
                <label for="cargo" class="col-sm-2 col-form-label">Cargo</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="cargo" value="{{ isset($vaga) ? $vaga->cargo : old('cargo') }}" required>
                </div>
            </div>

            <div class="mb-3 row">
                <label for="contratacao" class="col-sm-2 col-form-label">Modelo de Contratação</label>
                <div class="col-sm-10">
                  <select name="contratacao" id="contratacao" class="form-select">
                      @foreach (config('parameters.contratacao') as $cont_id => $cont_nome)
                          <option value="{{ $cont_id }}" {{ isset($vaga) && $vaga->contratacao == $cont_id || old('contratacao') == $cont_id ? 'selected' : '' }}>{{ $cont_nome }}</option>
                      @endforeach
                  </select>
                </div>
            </div>

            <div class="mb-3 row">
                <label for="descricao" class="col-sm-2 col-form-label">Descrição da Vaga</label>
                <div class="col-sm-10">
                  <textarea name="descricao" class="form-control" cols="30" rows="10">{!! isset($vaga) ? $vaga->descricao : old('descricao') !!}</textarea>
                </div>
            </div>

            <div class="row">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/vagas/index.blade.php
@extends('layouts.template')

@section('maincontent')
<h2 class="">Gerenciamento de Vagas</h2>

@if(Session::has('flash_message'))
    <div class="alert alert-success mb-5" role="alert">
        {{ Session::get('flash_message') }}
    </div>
@endif

<div class="container">
    <div class="row mb-5 mt-4">
        <div class="col">
            <form action="{{ route('painel.vagas.index') }}" method="get" class="row g-3 float-start">
                <div class="col-auto">
                  <label for="pesquisar" class="visually-hidden">Pesquisar...</label>
                  <input type="text" class="form-control" name="pesquisar" value="{{ request('pesquisar') }}" placeholder="Pesquisar por nome...">
                </div>
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary mb-3">Pesquisar</button>
                </div>
            </form>
            <a href="{{ route('painel.vagas.create') }}" class="btn btn-success btn-small float-end"><i class="bi bi-plus"></i> Adicionar</a>
        </div>
    </div>


    <a href="#" class="btn btn-outline-danger __action_remover"><i class="bi bi-trash"></i> Remover Selecionados</a>
    <form method="post" class="__form_remover" action="{{ route('painel.vagas.destroy-mass') }}">
        @csrf
        @method('DELETE')
        <input type="hidden" name="checados" class="checados" value="">
    </form>
    

    <table class="table table-hover">
        <thead>
            <tr>
                <td scope="col">&nbsp;</td>
                <td scope="col"><a href="{{ route('painel.vagas.index', ['pesquisar'=>request('pesquisar'), 'order' => 'public_id', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">ID</a></td>
                <td scope="col"><a href="{{ route('painel.vagas.index', ['pesquisar'=>request('pesquisar'), 'order' => 'cargo', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">Cargo</a></td>
                <td scope="col">N. Candidatos</td>
                <td scope="col"><a href="{{ route('painel.vagas.index', ['pesquisar'=>request('pesquisar'), 'order' => 'contratacao', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">Contratação</a></td>
                <td scope="col"><a href="{{ route('painel.vagas.index', ['pesquisar'=>request('pesquisar'), 'order' => 'status', 'orderby' => (strtolower(request('orderby')) == 'asc' ? 'desc' : 'asc')]) }}">Status</a></td>
                <td scope="col">&nbsp;</td>
                <td scope="col">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
        @forelse ($vagas as $vaga)
            <tr>
                <td scope="row">
                    <input type="checkbox" name="vagas[]" value="{{ $vaga->public_id }}" class="__checks">
                </td>
                <td>{{ $vaga->public_id }}</td>
                <td>{{ $vaga->cargo }}</td>
                <td>{{ $vaga->candidatos->count() }} Candidato{{ $vaga->candidatos->count() != 1 ? 's' : '' }}</td>
                <td>{{ config('parameters.contratacao.' . (int)$vaga->contratacao) }}</td>
                <td>
                    <a href="{{ route('painel.vagas.update-status', $vaga->public_id) }}" class="badge bg-{{ (int)$vaga->status == 0 ? 'warning' : 'success' }}">{{ config('parameters.status.' . (int)$vaga->status) }}</a>
                </td>
                <td>
                    <a href="{{ route('painel.vagas.edit', $vaga->public_id) }}" class="btn btn-info btn-small">Editar</a>
                </td>
                <td>
                    <form action="{{ route('painel.vagas.destroy', $vaga->public_id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-small">Excluir</button>
                    </form>
                </td>
            </tr>
        @empty
        <tr>
            <td colspan="6">
                Nenhuma vaga cadastrada no momento
            </td>
        </tr>
        @endforelse
        </tbody>
    </table>

    <div class="row justify-content-center">
        <div class="col">
            {{ $vagas->appends(['pesquisar'=>request('pesquisar'), 'order'=>request('order'), 'orderby'=>request('orderby')])->links() }}
        </div>
    </div>
</div>
@endsection